### ISSUE TITLE
能分享一下你这个二级域名的nginx的配置文件吗？包括前端静态和后端服务的代理。

### ISSUE THREAD

**Issue by saucxs** [wclimb/video-admin#7]

**Comment by wclimb** [comment]
最简单的配置
```
server {
    listen 80;
    server_name vue.wclimb.site;
    location / {
        proxy_pass http://127.0.0.1:3000;
    }
}
```

**Comment by saucxs** [comment]
但是如果是前后端分离的项目，前端静态转发和后盾服务代理，在服务器上启动的时候，启动地址：127.0.0.1:8361和127.0.0.1:8362，二级域名预警解析。
两个二级域名nginx.conf这样配置，但是还是只访问第一个？
`	upstream weekly_node {
        server 127.0.0.1:8361;
    }
	upstream vue_node {
        server 127.0.0.1:8362;
    }
	server {
		listen 80;
		server_name weekly.mwcxs.top;
		#前端静态打包
		location / {
			alias /home/fastdfs/nginx/weekly/dist
            index  index.html index.htm;
            try_files $uri $uri/ /index.html last;
		}
		#后端服务代理转发
		location / {
			proxy_pass http://weekly_node;
			
		}
    }
	server {
		listen 80;
		server_name vue.mwcxs.top;
		#前端静态打包
		location / {
			alias /home/fastdfs/nginx/vue/dist
            index  index.html index.htm;
            try_files $uri $uri/ /index.html last;
		}
		#后端服务代理转发
		location / {
			proxy_pass http://vue_node;
			
		}
    }`
